### PR TITLE
Update Coq versions

### PR DESCRIPTION
**Pull request by jjhugues**
This project compiles fine with latest Coq version. I propose the following updates to the opam file and GitHub workflow.

### CODE REVIEW

**Comment by DmxLarchey** [comment]
Hi @jjhugues I did remove the `coq-dev` target because it fails in the CI.

**Comment by DmxLarchey** [comment]
I will release it as `v1.1.1` for `opam` publication.

**Comment by DmxLarchey** [comment]
Btw @jjhugues, would you prefer this library to be released under the `MPL 2.0` licence ?

**Comment by DmxLarchey** [comment]
Btw @sei-jhugues, would you prefer this library to be released under the `MPL 2.0` licence ?

**Comment by yoogx** [comment]
I think coq-dev is future 8.20, so opam should be
  "coq" {>= "8.14" & < "8.21~"} 
and not 8.20 as I wrote

MPL license would be nice, I did not realize this is the license proposed by coq-community at https://github.com/coq-community/manifesto

**Comment by DmxLarchey** [comment]
> I think coq-dev is future 8.20, so opam should be "coq" {>= "8.14" & < "8.21~"} and not 8.20 as I wrote

Ok I do it.

> MPL license would be nice, I did not realize this is the license proposed by coq-community at https://github.com/coq-community/manifesto

Fine let us switch to this license since you are OK with it.

**Pull request merged**
